sudo: false

language: scala

jdk:
  - openjdk11

scala:
  - 2.13.1
  - 2.12.10

script: sbt --warn ++$TRAVIS_SCALA_VERSION clean coverage test

after_success: sbt ++$TRAVIS_SCALA_VERSION coverageReport coverageAggregate coveralls

notifications:
  slack:
    on_success: never
    on_failure: always
    rooms:
      secure: "YKKZen3NANGs1T6wB8DH1MwMs8rIRCClRjytjQSF169qtstQXgGmLwvOO9JzBTa3Ax5EoDZ5WWGialWw3VaUkAtO03ZT3S3ih8ocNg69TPz//p344TZTpx7UC9AgozzkYesPzG4M1Q1G0CRIPeRQAoOKXa61qiyDCX/Du0u6ldrENW5e8+xixe+AzUOvdytKFWin9SdnpXPjQkhyi5HbLJADEdTmw+nxQH+W1aqRomT5zR5hO4TFpA3vefjkVWZMle3aZLG4y/kvooJKiyTdJG68O9WrVpa5IgI7gT81uKPrhccvpA5p/bgJHNdxzSIcPh0/lGxGmEZNrwCnnEyy2wRI2EzDGecOqR1vlvk+krVsHIwBfz/1HiPjTD4Kwfxh7F1dyNbDsDo6c/LNDrMWYW/4bNulbPul7GRzNlGnZiv1mTmItD86rVaiAD/ZzWZOisWvZVaY0iPSSEOBC4LnzO2NplSf+GokbnCnLFsV2hoDw+Ba2Gmlo7QAHTJYM9VBKXUWrKwK3syKoa2DxG22W7XvQfI8XtimfBs8ixJBNFYfA0WI4RjHzyPAK2ZEgzLRdrqzKKG4VNJt1g30znQ1esWjTmbw9qYnBVLH/dXc0fTA4F8A7li4HglR+aBag1EJnIMXkZu4BcpMU6SLIYV6BJ0PuWKJnnBHjftNgmXqKbc="

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete